language: go

branches:
  only:
  - /.*/

service:
  - docker

install:
  # Note(tony): TravisCI's native `go get ${gobuild_args} ./...` failed with
  # `/usr/bin/ld: final link failed: Bad value`, the cause is the system linker
  # being not up to date: https://github.com/golang/go/issues/15038
  # So I decided to skip install, and go get inside sqlflow:latest image
  # Ref build: https://travis-ci.com/sql-machine-learning/sqlflow/builds/107870583
  - echo "skip install"

script:
  # Please be aware that here we use the prebuilt Docker image
  # sqlflow/gohive:dev automatically built by DockerHub from
  # docker/Dockerfile in this repo.  The reason that we don't rebuild
  # this image for every PR is that it takes a long time to build --
  # especially the downloading of Hadoop and Hive.  Using this
  # prebuilt image for CI requires that if, in any PR, we want to
  # change the Docker image, we'd have to split that PR into two --
  # one changing the Docker image, which must be merged before the
  # other one that changes the source code to be CI'ed with the
  # updated Docker image.
  - docker run --rm -v $GOPATH:/go -w /go/src/sqlflow.org/gohive sqlflow/gohive:dev bash test.sh
  - docker run -e WITH_HS2_PAM_AUTH=ON --rm -v $GOPATH:/go -w /go/src/sqlflow.org/gohive sqlflow/gohive:dev bash test.sh
